spring.application.name=InductionApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=ENC(5hi65yWnVynl5WI+Al+WkeqR1ac9xMW9gmDbGGK5kXDqd71XYa3ROPRgtuVic5MH)
spring.datasource.password=ENC(wtEVPQrmxDUNot6ZZF0HJMbrBPyit4ZxviY0Y/ZBRQDERC9LGN/MbPKiCZXymPGd)
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
debug=true

